openapi: '3.0.2'
info:
  title: iCloud API
  version: '1.0.0'
servers:
  - url: https://api.server.test/v1
paths:
  /isalive:
    get:
      responses:
        '204':
          description: No Content
        '429':
          description: Too Many Requests
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
  /ishealthy:
    parameters:
    - in: header
      name: X-APPLE-ID
      description: ''
      required: true
      schema:
        type: string
    - in: header
      name: X-PASSWORD
      description: ''
      required: true
      schema:
        type: string
    get:
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '429':
          description: Too Many Requests
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Timeout
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
  /reminders/lists:
    get:
      parameters:
        - in: header
          name: X-APPLE-ID
          description: ''
          required: true
          schema:
            type: string
        - in: header
          name: X-PASSWORD
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/lists'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '429':
          description: Too Many Requests
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Timeout
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
  /reminders/lists/{list}:
    get:
      parameters:
        - in: header
          name: X-APPLE-ID
          description: ''
          required: true
          schema:
            type: string
        - in: header
          name: X-PASSWORD
          description: ''
          required: true
          schema:
            type: string
        - in: path
          name: list
          description: 'The name of the list.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/list'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '429':
          description: Too Many Requests
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Timeout
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
    post:
      parameters:
        - in: header
          name: X-APPLE-ID
          description: ''
          required: true
          schema:
            type: string
        - in: header
          name: X-PASSWORD
          description: ''
          required: true
          schema:
            type: string
        - in: path
          name: list
          description: 'The name of the list.'
          required: true
          schema:
            type: string
      requestBody:
        description: ''
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/reminder'
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
              description: URL to the newly created resource
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '429':
          description: Too Many Requests
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Timeout
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
  /reminders/lists/{list}/{id}:
    put:
      parameters:
        - in: header
          name: X-APPLE-ID
          description: ''
          required: true
          schema:
            type: string
        - in: header
          name: X-PASSWORD
          description: ''
          required: true
          schema:
            type: string
        - in: path
          name: list
          description: 'The name of the list.'
          required: true
          schema:
            type: string
        - in: path
          name: id
          description: 'The ID of the reminder.'
          required: true
          schema:
            type: string
      requestBody:
        description: ''
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/reminder'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '429':
          description: Too Many Requests
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Timeout
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
    patch:
      parameters:
        - in: header
          name: X-APPLE-ID
          description: ''
          required: true
          schema:
            type: string
        - in: header
          name: X-PASSWORD
          description: ''
          required: true
          schema:
            type: string
        - in: path
          name: list
          description: 'The name of the list.'
          required: true
          schema:
            type: string
        - in: path
          name: id
          description: 'The ID of the reminder.'
          required: true
          schema:
            type: string
      requestBody:
        description: ''
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/completed'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '429':
          description: Too Many Requests
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Timeout
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
    delete:
      parameters:
        - in: header
          name: X-APPLE-ID
          description: ''
          required: true
          schema:
            type: string
        - in: header
          name: X-PASSWORD
          description: ''
          required: true
          schema:
            type: string
        - in: path
          name: list
          description: 'The name of the list.'
          required: true
          schema:
            type: string
        - in: path
          name: id
          description: 'The ID of the reminder.'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '429':
          description: Too Many Requests
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
        '504':
          description: Gateway Timeout
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  schemas:
    address:
      type: object
      properties:
        street:
          type: string
          example: 'Brompton Road'
        houseNumber:
          type: string
          example: '87-135'
        zipCode:
          type: string
          example: 'SW1X 7XL'
        city:
          type: string
          example: 'London'
        country:
          type: string
          example: 'United Kingdom'
    reminder:
      type: object
      required: [title]
      properties:
        title:
          type: string
          example: 'Get a birthday present for Lisa'
        description:
          type: string
          example: 'Call Robert to ask what Lisa likes.'
        priority:
          type: string
          enum:
            - low
            - medium
            - heigh
          example: 'medium'
        locationName:
          type: string
          example: Harrods
        address:
          $ref: '#/components/schemas/address'
        latitude:
          type: number
          format: double
          example: 51.4992917
        longitude:
          type: number
          format: double
          example: -0.162811
        radius:
          type: number
          format: double
          example: 1000
        proximity:
          type: string
          enum:
            - ARRIVE
            - DEPART
          example: ARRIVE
        alarm:
          type: string
          format: date-time
          example: '2021-12-31T00:00:00'
        completed:
          type: boolean
          example: false
    list:
      type: object
      required: [id, name, reminders]
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: List 1
        reminders:
          type: array
          items:
            $ref: '#/components/schemas/reminder'
    lists:
      type: array
      items:
        $ref: '#/components/schemas/list'
    completed:
      type: object
      properties:
        completed:
          type: boolean
    errorSource:
        type: object
        properties:
          pointer:
            type: string
            example: 'pointer: /reminders/lists/example'
    error:
      required: ['code', 'message']
      properties:
        status:
          type: string
          example: '400'
        source:
          $ref: '#/components/schemas/errorSource'
        title:
          type: string
          example: 'Invalid input.'
        detail:
          type: string
          example: 'Reminder must contain a title.'
    errorResponse:
      type: object
      properties:
        errors:
            type: array
            items:
              $ref: "#/components/schemas/error"
